const fakeData = [{
    "id": 1,
    "name": "HTML",
    "price": 20,
  }, {
    "id": 2,
    "name": "CSS",
    "price": 20,
  }, {
    "id": 3,
    "name": "Bootstrap",
    "price": 20,
  }, {
    "id": 4,
    "name": "JavaScript",
    "price": 50,
  }, {
    "id": 5,
    "name": "Express",
    "price": 30,
  }, {
    "id": 6,
    "name": "NodeJS",
    "price": 30,
  }, {
    "id": 7,
    "name": "React",
    "price": 100,
  }, {
    "id": 8,
    "name": "React-Native",
    "price": 50,
  }, {
    "id": 9,
    "name": "React-Redux",
    "price": 60,
  }, {
    "id": 10,
    "name": "MongoDB",
    "price": 40,
  }, {
    "id": 11,
    "name": "MySQL",
    "price": 50,
  }, {
    "id": 12,
    "name": "Python",
    "price": 70,
  }, {
    "id": 13,
    "name": "Django",
    "price": 60,
  }, {
    "id": 14,
    "name": "C++",
    "price": 40,
  }, {
    "id": 15,
    "name": "C#",
    "price": 40
  }];

  export default fakeData;